{{- if and (not .Values.session.existingSecretName) .Values.session.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graylog-auth-proxy.fullname" . }}-session
  labels:
    {{- include "graylog-auth-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.session.existingSecretKey }}: {{ .Values.session.key | b64enc | quote }}
{{- end }}
