{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "graylog-auth-proxy.fullname" . }}
  labels:
    {{- include "graylog-auth-proxy.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "graylog-auth-proxy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      scheme: https
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
      tlsConfig:
        insecureSkipVerify: true
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
