{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graylog-auth-proxy.serviceAccountName" . }}
  labels:
    {{- include "graylog-auth-proxy.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if or .Values.workloadIdentity.enabled (eq .Values.oidc.mode "workloadIdentity") }}
    {{- with .Values.workloadIdentity.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
